name: publish

on:
  workflow_dispatch:

concurrency:
  group: "publish"
  cancel-in-progress: true

jobs:
  publish:
    environment: MavenRelease
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish
        uses: gradle/gradle-build-action@v2
        env:
          ORG_GRADLE_PROJECT_ossrhUser: ${{ secrets.OSSRH_USER }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_stagingProfile: ${{ secrets.STAGING_PROFILE_ID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.GPG_KEYID }}
        with:
          arguments: "publishToSonatype closeAndReleaseStagingRepository"